    /*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package inventory_view;

import inventory_controller.controllerProduk;
import invetory_db.koneksi;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Windows 10
 */
public class viewProduk extends javax.swing.JFrame {
    private controllerProduk cP;
    private DefaultTableModel tabel;

    /**
     * Creates new form viewBarang
     */
    public viewProduk() {
        initComponents();
        
        cP = new controllerProduk(this);
        tabel = new DefaultTableModel();
        listproduk_TB1.setModel(tabel);
        
        tabel.addColumn("Id Produk");
        tabel.addColumn("Nama Produk");
        tabel.addColumn("Kategori");
        tabel.addColumn("Harga Satuan");
        tabel.addColumn("Stok");
        
        cP.kontrol();
        TampilTabel();
    }
    public JTextField getHarga() {
        return hargaSatuan_TF4;
    }

    public JTextField getIdProduk() {
        return idProduk_TF1;
    }

    public JTextField getKategori() {
        return kategori_TF3;
    }

    public JTextField getNamaProduk() {
        return namaProduk_TF2;
    }

    public JTextField getStok() {
        return stok_TF5;
    }

    public JButton getBatal() {
        return batal_BT1;
    }

    public JButton getUbah() {
        return ubah_BT3;
    }

    public JButton getHapus() {
        return hapus_BT2;
    }

    public JButton getSimpan() {
        return simpan_BT4;
    }
   
    
    private void TampilTabel (){
        tabel.getDataVector().removeAllElements();
        tabel.fireTableDataChanged();
        
        String sql = "SELECT * FROM produk ";
        try {
            Statement stat = (Statement) koneksi.getKoneksi().createStatement();
            ResultSet res  = stat.executeQuery(sql);
            
            while (res.next()){
                Object[] hasil;
                hasil = new Object[5];
                hasil[0] = res.getString("idProduk");
                hasil[1] = res.getString("namaProduk");
                hasil[2] = res.getString("kategori");
                hasil[3] = res.getString("hargaProduk");
                hasil[4] = res.getString("stok"); 
                
                tabel.addRow(hasil);
                
            }
            
        } catch (SQLException ex) {
            System.out.println("Terjadi Error");;
        }  
    }
    
    private void AmbilDataTabel(){
        int index = listproduk_TB1.getSelectedRow();
        String idproduk = String.valueOf(listproduk_TB1.getValueAt(index, 0));
        String namaproduk = String.valueOf(listproduk_TB1.getValueAt(index, 1));
        String kategori = String.valueOf(listproduk_TB1.getValueAt(index, 2));
        String harga = String.valueOf(listproduk_TB1.getValueAt(index, 3));
        String stok = String.valueOf(listproduk_TB1.getValueAt(index, 4));
        
        
        idProduk_TF1.setText(idproduk);
        namaProduk_TF2.setText(namaproduk);
        kategori_TF3.setText(kategori);
        hargaSatuan_TF4.setText(harga);
        stok_TF5.setText(stok);
        
        
        cP.kontroldua();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listproduk_TB1 = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        hapus_BT2 = new javax.swing.JButton();
        batal_BT1 = new javax.swing.JButton();
        idProduk_TF1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        ubah_BT3 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        simpan_BT4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        stok_TF5 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        hargaSatuan_TF4 = new javax.swing.JTextField();
        kategori_TF3 = new javax.swing.JTextField();
        namaProduk_TF2 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        cari_TF6 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        listproduk_TB1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        listproduk_TB1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listproduk_TB1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listproduk_TB1);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("List Produk");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Manage Produk", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 18))); // NOI18N

        hapus_BT2.setText("HAPUS");
        hapus_BT2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hapus_BT2ActionPerformed(evt);
            }
        });

        batal_BT1.setText("BATAL");
        batal_BT1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                batal_BT1ActionPerformed(evt);
            }
        });

        idProduk_TF1.setEnabled(false);
        idProduk_TF1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idProduk_TF1ActionPerformed(evt);
            }
        });

        jLabel1.setText("ID Produk");

        jLabel2.setText("Nama Produk");

        ubah_BT3.setText("UBAH");
        ubah_BT3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ubah_BT3ActionPerformed(evt);
            }
        });

        jLabel3.setText("Kategori");

        simpan_BT4.setText("SIMPAN");
        simpan_BT4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                simpan_BT4ActionPerformed(evt);
            }
        });

        jLabel4.setText("Harga Satuan");

        stok_TF5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                stok_TF5ActionPerformed(evt);
            }
        });

        jLabel6.setText("Stok");

        hargaSatuan_TF4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                hargaSatuan_TF4ActionPerformed(evt);
            }
        });

        kategori_TF3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kategori_TF3ActionPerformed(evt);
            }
        });

        namaProduk_TF2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                namaProduk_TF2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(kategori_TF3, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(stok_TF5, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 97, Short.MAX_VALUE)
                        .addComponent(namaProduk_TF2, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(idProduk_TF1, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(hargaSatuan_TF4, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jLabel6)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(9, 9, 9)
                            .addComponent(batal_BT1)
                            .addGap(18, 18, 18)
                            .addComponent(hapus_BT2)
                            .addGap(18, 18, 18)
                            .addComponent(ubah_BT3)
                            .addGap(27, 27, 27)
                            .addComponent(simpan_BT4)))
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(51, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(idProduk_TF1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(namaProduk_TF2, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kategori_TF3, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(hargaSatuan_TF4, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(27, 27, 27)
                .addComponent(stok_TF5, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(112, 112, 112))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addContainerGap(267, Short.MAX_VALUE)
                    .addComponent(jLabel6)
                    .addGap(84, 84, 84)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(simpan_BT4)
                        .addComponent(ubah_BT3)
                        .addComponent(hapus_BT2)
                        .addComponent(batal_BT1))
                    .addContainerGap()))
        );

        jLabel8.setText("Cari");

        cari_TF6.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                cari_TF6KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                cari_TF6KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 62, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(215, 215, 215))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(27, 27, 27)
                                .addComponent(cari_TF6, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 440, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(40, 40, 40))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(36, 36, 36)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cari_TF6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(26, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void namaProduk_TF2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_namaProduk_TF2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_namaProduk_TF2ActionPerformed

    private void kategori_TF3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kategori_TF3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_kategori_TF3ActionPerformed

    private void hargaSatuan_TF4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hargaSatuan_TF4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_hargaSatuan_TF4ActionPerformed

    private void stok_TF5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_stok_TF5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_stok_TF5ActionPerformed

    private void simpan_BT4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_simpan_BT4ActionPerformed
        // TODO add your handling code here:\
        cP.simpan();
        
    }//GEN-LAST:event_simpan_BT4ActionPerformed

    private void ubah_BT3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ubah_BT3ActionPerformed
        // TODO add your handling code here:
        cP.update();
        TampilTabel();
    }//GEN-LAST:event_ubah_BT3ActionPerformed

    private void idProduk_TF1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idProduk_TF1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_idProduk_TF1ActionPerformed

    private void batal_BT1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_batal_BT1ActionPerformed
        // TODO add your handling code here:
        cP.kontrol();
        cP.clear();
    }//GEN-LAST:event_batal_BT1ActionPerformed

    private void hapus_BT2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_hapus_BT2ActionPerformed
        // TODO add your handling code here:
        cP.delete();
        TampilTabel();
    }//GEN-LAST:event_hapus_BT2ActionPerformed

    private void listproduk_TB1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listproduk_TB1MouseClicked
        // TODO add your handling code here:
        AmbilDataTabel();
    }//GEN-LAST:event_listproduk_TB1MouseClicked

    private void cari_TF6KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cari_TF6KeyReleased
        // TODO add your handling code here:
        tabel.getDataVector().removeAllElements();
        tabel.fireTableDataChanged();
        String sql = "SELECT * FROM produk WHERE namaProduk like '%"+cari_TF6.getText()+"%'";
        try {
            Statement stat = (Statement) koneksi.getKoneksi().createStatement();
            ResultSet res  = stat.executeQuery(sql);
            
            while (res.next()){
                Object[] hasil;
                hasil = new Object[5];
                hasil[0] = res.getString("idProduk");
                hasil[1] = res.getString("namaProduk");
                hasil[2] = res.getString("kategori");
                hasil[3] = res.getString("hargaProduk");
                hasil[4] = res.getString("stok"); 
                
                tabel.addRow(hasil);
                
            }
            
        } catch (SQLException ex) {
            System.out.println("Terjadi Error"+ex);
        }  
    }//GEN-LAST:event_cari_TF6KeyReleased

    private void cari_TF6KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_cari_TF6KeyPressed
        // TODO add your handling code here:
    }//GEN-LAST:event_cari_TF6KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(viewProduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(viewProduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(viewProduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(viewProduk.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new viewProduk().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton batal_BT1;
    private javax.swing.JTextField cari_TF6;
    private javax.swing.JButton hapus_BT2;
    private javax.swing.JTextField hargaSatuan_TF4;
    private javax.swing.JTextField idProduk_TF1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField kategori_TF3;
    private javax.swing.JTable listproduk_TB1;
    private javax.swing.JTextField namaProduk_TF2;
    private javax.swing.JButton simpan_BT4;
    private javax.swing.JTextField stok_TF5;
    private javax.swing.JButton ubah_BT3;
    // End of variables declaration//GEN-END:variables
}
